[env:esp32_bat]
platform = espressif32
board = lolin_d32
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
build_flags =
    -DPLATFORM_ESP32

[env:esp32c3_zas]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = min_spiffs.csv
monitor_speed = 115200
lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
build_flags =
    -DPLATFORM_C3
